package cn.com.mustache.plugin.schemalens.extractor

import cn.com.mustache.plugin.schemalens.framework.TableStructureLogger
import cn.com.mustache.plugin.schemalens.model.ColumnStructure
import com.intellij.database.model.DasColumn
import com.intellij.database.psi.DbTable
import com.intellij.database.util.DasUtil

/**
 * Table structure extractor - extracts column information
 */
object TableStructureExtractor {
    fun extract(table: DbTable): List<ColumnStructure> {
        return try {
            DasUtil.getColumns(table)
                .toList()
                .filterIsInstance<DasColumn>()
                .map { it.toColumnStructure() }
        } catch (e: Exception) {
            TableStructureLogger.warn("Failed to extract columns from ${table.name}", e)
            emptyList()
        }
    }

    private fun DasColumn.toColumnStructure(): ColumnStructure {
        val dataTypeLabel = dasType.specification
        val defaultValue = default?.takeIf { it.isNotBlank() }

        return ColumnStructure(
            position = position.toInt(),
            name = name,
            dataType = dataTypeLabel,
            nullable = !isNotNull,
            defaultValue = defaultValue,
            primaryKey = DasUtil.isPrimary(this),
            autoIncrement = DasUtil.isAutoGenerated(this),
            comment = comment.orEmpty()
        )
    }
}

